import type { DestructionStylePreset, StylizedWhispConfig } from '../types/destructionStyle';
import type { ShatterConfig } from '../types/shatter';

export const STYLIZED_WHISP_STYLE_CONFIG: StylizedWhispConfig = {
  kind: 'stylized-whisp',
  strike: {
    direction: 'falling-diagonal',
    angle: 40,
    visible: true,
  },
  fracture: {
    fragmentCount: 16,
    spread: 0.29,
    force: 0.62,
    rotation: 0.46,
  },
  extinction: {
    shardLifetime: 300,
    fadeAmount: 1,
    speed: 0.7,
  },
  smoke: {
    shardAmount: 0.31,
    shardConversionSpeed: 0.7,
    centralAmount: 0.28,
    centralConversionSpeed: 0.8,
  },
  whisp: {
    whispAmount: 0.45,
    whispLength: 0.65,
    curl: 0.45,
    rise: 0.55,
  },
  audio: {
    objectWeight: 'auto',
    impactWeight: 0.65,
    debrisLevel: 0.55,
    whispLevel: 0.35,
  },
  appearance: {
    visualStyle: 'stylized',
  },
};

const STYLIZED_WHISP_ENGINE_DEFAULTS: ShatterConfig = {
  fragmentCount: 16,
  breakStrength: 0.62,
  gravity: 0.35,
  bounce: 0.08,
  rotation: 0.46,
  particles: 'medium',
  screenShake: 'low',
  sound: true,
  soundSource: 'procedural',
  customSoundVolume: 1,
  background: 'transparent',
  impactMode: 'auto',
  seed: undefined,
  airFriction: 0.028,
  fragmentFriction: 0.45,
  restitution: 0.056,
  impactRadius: 0.4,
  forceVariation: 0.35,
  rotationVariation: 0.5,
  floorEnabled: true,
  floorY: 0.92,
  particleLifetime: 450,
  animationDuration: 540,
  exportFps: 60,
};

export const STYLIZED_WHISP_PRESET: DestructionStylePreset = {
  id: 'stylized-whisp',
  name: 'Stylized Whisp',
  description: 'Fast directional smash with compact shards and an extinction whisp.',
  defaultGlobalConfig: {
    background: STYLIZED_WHISP_ENGINE_DEFAULTS.background,
    sound: STYLIZED_WHISP_ENGINE_DEFAULTS.sound,
    soundSource: STYLIZED_WHISP_ENGINE_DEFAULTS.soundSource,
    customSoundVolume: STYLIZED_WHISP_ENGINE_DEFAULTS.customSoundVolume,
    impactMode: STYLIZED_WHISP_ENGINE_DEFAULTS.impactMode,
    seed: STYLIZED_WHISP_ENGINE_DEFAULTS.seed,
    exportFps: STYLIZED_WHISP_ENGINE_DEFAULTS.exportFps,
  },
  defaultStyleConfig: STYLIZED_WHISP_STYLE_CONFIG,
  defaultEngineConfig: STYLIZED_WHISP_ENGINE_DEFAULTS,
  timeline: {
    strikeStart: 0,
    impact: 80,
    fracture: 88,
    motionStart: 88,
    extinctionStart: 205,
    cleanupStart: 390,
    complete: 540,
  },
  fractureProfile: {
    kind: 'stylized',
    impactDensity: 0.72,
    directionalBias: 0.24,
    strikeVector: { x: Math.cos(40 * Math.PI / 180), y: Math.sin(40 * Math.PI / 180) },
  },
  motionProfile: {
    kind: 'stylized',
    strikeVector: { x: Math.cos(40 * Math.PI / 180), y: Math.sin(40 * Math.PI / 180) },
    directionalWeight: 0.78,
    radialWeight: 0.12,
    variationWeight: 0.1,
    spread: STYLIZED_WHISP_STYLE_CONFIG.fracture.spread,
    force: STYLIZED_WHISP_STYLE_CONFIG.fracture.force,
    rotation: STYLIZED_WHISP_STYLE_CONFIG.fracture.rotation,
    classSpeed: {
      primary: [0.68, 0.8],
      secondary: [0.9, 1.02],
      micro: [1.04, 1.18],
    },
    gravity: {
      initialScale: 0.12,
      rampStart: 100,
      rampEnd: 250,
    },
  },
  extinctionProfile: {
    kind: 'stylized',
    baseLifetime: STYLIZED_WHISP_STYLE_CONFIG.extinction.shardLifetime,
    classLifetime: {
      primary: 1,
      secondary: 0.78,
      micro: 0.55,
    },
    lifetimeVariation: 0.12,
    extinctionStartRatio: 0.72,
    fadeAmount: STYLIZED_WHISP_STYLE_CONFIG.extinction.fadeAmount,
    scaleEnd: 0.78,
    speed: STYLIZED_WHISP_STYLE_CONFIG.extinction.speed,
    whispAmount: STYLIZED_WHISP_STYLE_CONFIG.whisp.whispAmount,
    whispLength: STYLIZED_WHISP_STYLE_CONFIG.whisp.whispLength,
    curl: STYLIZED_WHISP_STYLE_CONFIG.whisp.curl,
    rise: STYLIZED_WHISP_STYLE_CONFIG.whisp.rise,
  },
  smokeProfile: {
    kind: 'stylized',
    ...STYLIZED_WHISP_STYLE_CONFIG.smoke,
  },
  audioProfile: {
    kind: 'stylized',
    ...STYLIZED_WHISP_STYLE_CONFIG.audio,
  },
  defaultVisualStyle: STYLIZED_WHISP_STYLE_CONFIG.appearance.visualStyle,
  capabilities: {
    physicalSettings: false,
    strikeSettings: true,
    extinctionSettings: true,
    whispSettings: true,
    sizeAwareAudio: true,
  },
};
